workspace(
    name = "client",
    managed_directories = {"@npm": ["node_modules"]},
)

## For Node.js/npm
# ref. https://bazelbuild.github.io/rules_nodejs/
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "2eca5b934dee47b5ff304f502ae187c40ec4e33e12bcbce872a2eeb786e23269",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.4.1/rules_nodejs-1.4.1.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "npm_install")

# To find SHA256 hash value, find them in SHASUMS256.txt in each version directories.
# https://nodejs.org/dist/
node_repositories(
    node_version = "13.10.1",
    node_repositories = {
        "13.10.1-linux_amd64": ("node-v13.10.1-linux-x64.tar.xz", "node-v13.10.1-linux-x64", "69d69165282d88f321e751f03ee5d3370db65e5ca4c587af24994b12f31d4827"),
        "13.10.1-darwin_amd64": ("node-v13.10.1-darwin-x64.tar.xz", "node-v13.10.1-darwin-x64", "9b5281ef32d311c570a9fc5f7bcbc187b2693d208e2990b14d8c0f41e3a3a500"),
        "13.10.1-windows_amd64": ("node-v13.10.1-win-x64.7z", "node-v13.10.1-win-x64", "52d684cf5f0fe4f261a9b536c4d112c7ec2695eb62bb8fb32ec32b11e39496bb"),
    },
    node_urls = ["https://nodejs.org/dist/v{version}/{filename}"],
    package_json = ["//:package.json"],
)

npm_install(
    name = "npm",
    package_json = "//:package.json",
    package_lock_json = "//:package-lock.json",
)